name: Lint and Format Checks

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  workflow_dispatch:

jobs:
  lint_and_format_check:
    name: Lint and Format Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install node modules
        run: npm ci --cache --prefer-offline --no-audit

      - name: Typescript lint
        working-directory: .
        run: npm run lint

      - name: Prettier check
        working-directory: .
        run: npm run format:check
